Create README.md
niksaz/gRPChat pull request #1
Opened 2018-05-03 21:08 UTC by niksaz

2018-05-30 15:54 UTC, yurii-litvinov requested changes
- Swing? Выглядит сурово, как в начале 2000-х (это, очевидно, можно не править)
- Форма позволяет себя сжать до неприличных размеров
- Нет заголовка окна
- Список сообщений не скроллится, поэтому беседы должны быть краткими, иначе ответы невозможно будет прочитать :)

В остальном всё ок, но пользовательский интерфейс всё-таки поправьте, пожалуйста.

2018-05-30 15:54 UTC, yurii-litvinov commented on README.md
> +To run the app with gradle you need to have [Google protobuf compiler](https://github.com/google/protobuf/releases).
Он же сам качается при сборке, gradle protobuf plugin всё делает как надо

2018-05-30 15:54 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mesau/GUIRunner.java
> +    editorPane.setEnabled(false);
Это делает текст на ней бледным и нечитаемым. Swing не умеет enabled, но нередактируемых текстовых панелей? Можно просто Label-ы в лейаут добавлять

2018-05-30 15:54 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mesau/GUIServiceStrategy.java
> +  public abstract void sendMessage(Message message);
А чего он не интерфейс?

2018-05-30 16:09 UTC, niksaz commented on README.md
> +To run the app with gradle you need to have [Google protobuf compiler](https://github.com/google/protobuf/releases).
Вы правы: это с tutorial-а осталось Google-а без этого плагина.

2018-05-30 16:14 UTC, niksaz commented on src/main/java/ru/spbau/mesau/GUIRunner.java
> +    editorPane.setEnabled(false);
Там действительно есть просто .setEditable(): можно было бы и почитать мне. ;)

2018-05-30 16:21 UTC, niksaz commented on src/main/java/ru/spbau/mesau/GUIServiceStrategy.java
> +  public abstract void sendMessage(Message message);
Казалось, что стратегии заключают какие-то алгоритмы и вряд ли  кто-нибудь захочет его вмешивать. Но на данный момент нет никаких весомых оснований для класса. И наверняка никто не захочет стратегии параметризировать. Но запретить наследование можно было бы. ;)

2018-05-30 16:41 UTC, niksaz commented
Даже IntelliJ IDEA все еще использует Swing. (:
Слишком строго судите для прототипа терминального приложения. ;) Спасибо вам за это. Исправили ваши замечания.

2018-05-30 16:46 UTC, niksaz commented
Оцените, пожалуйста, еще раз @yurii-litvinov.

2018-05-30 20:36 UTC, yurii-litvinov approved these changes
👍

2018-05-31 06:18 UTC, niksaz commented
Благодарим вас за проверку, @yurii-litvinov.

2018-05-31 06:18 UTC, merged